"""Gate 8.0a -- permutation equivariance and the automorphism invariant of the Phase-8 LGM.

The theorem being tested: equivariance gives f(A^s)_{s(i)s(j)} = f(A)_{ij}, and an automorphism has
A^s = A, so the score matrix is constant on the orbits of Aut(G) acting on PAIRS, and node states
are constant on node orbits as vectors.

Three traps this file is written to avoid.

  * Node-orbit equivalence does NOT imply the pairs built from those nodes are equivalent. Petersen
    is vertex-transitive, yet (0,1) is an edge and (0,2) is not; its 45 pairs fall into exactly two
    orbits. Assertions are therefore made over PAIR orbits, never over pairs whose endpoints merely
    share a node orbit, and never as an inequality ACROSS orbits.
  * No metric is asserted. On a provably constant score matrix roc_auc_score returns 0.5533 in
    float32, because orbit-equivalent nodes sit at different memory offsets, their reductions run in
    a different order, and float non-associativity leaves a residual that is never exactly zero --
    and AUROC swings across its whole range on such ties. Equality of outputs is the invariant;
    AUROC is not.
  * Vertex-transitive graphs make the assertion vacuous here: the theorem forces every node state
    equal and the decoder reads node states only, so the whole matrix collapses to one constant and
    a broken constant-output model passes identically. P_6 and K_{2,3} (several node orbits) carry
    the assertion; Petersen is kept as a separate, explicitly labelled collapse test.

Automorphism generators are hard-coded and closed by BFS rather than taken from networkx (which is
installed): the ground truth stays auditable and version-independent. Everything runs in float64 on
CPU in eval() on the unmasked graph with uniform edge values -- non-uniform values would shrink the
group to its colour-preserving subgroup.
"""
import pytest
import torch

from g2l.lgm import LGM, RawGraph

D, LAYERS, HEADS, TOL = 32, 2, 4, 1e-10


# ------------------------------------------------------------------ groups, orbits, graphs

def close_group(gens: list[list[int]], n: int) -> list[tuple[int, ...]]:
    """Every permutation generated by `gens`, found by BFS from the identity."""
    seen, frontier = {tuple(range(n))}, [tuple(range(n))]
    while frontier:
        p = frontier.pop()
        for g in gens:
            q = tuple(g[p[i]] for i in range(n))
            if q not in seen:
                seen.add(q)
                frontier.append(q)
    return sorted(seen)


class _UF:
    def __init__(self, n):
        self.p = list(range(n))

    def find(self, x):
        while self.p[x] != x:
            self.p[x] = self.p[self.p[x]]
            x = self.p[x]
        return x

    def union(self, a, b):
        ra, rb = self.find(a), self.find(b)
        self.p[ra] = rb

    def blocks(self):
        out = {}
        for x in range(len(self.p)):
            out.setdefault(self.find(x), []).append(x)
        return list(out.values())


def node_orbits(group, n):
    uf = _UF(n)
    for p in group:
        for i in range(n):
            uf.union(i, p[i])
    return uf.blocks()


def pair_orbits(group, n):
    pairs = [(i, j) for i in range(n) for j in range(i + 1, n)]
    at = {q: k for k, q in enumerate(pairs)}
    uf = _UF(len(pairs))
    for p in group:
        for k, (i, j) in enumerate(pairs):
            a, b = sorted((p[i], p[j]))
            uf.union(k, at[(a, b)])
    return [[pairs[k] for k in blk] for blk in uf.blocks()]


def dense(n, edges):
    A = torch.zeros(n, n, dtype=torch.float64)
    for i, j in edges:
        A[i, j] = A[j, i] = 1.0
    return A


def path6():
    return 6, dense(6, [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)]), [[5, 4, 3, 2, 1, 0]]


def k23():
    edges = [(a, b) for a in (0, 1) for b in (2, 3, 4)]
    return 5, dense(5, edges), [[1, 0, 2, 3, 4], [0, 1, 3, 2, 4], [0, 1, 3, 4, 2]]


def petersen():
    """Kneser K(5,2): the ten 2-subsets of {0..4}, adjacent iff disjoint. Aut = S_5, order 120."""
    verts = [(i, j) for i in range(5) for j in range(i + 1, 5)]
    at = {v: k for k, v in enumerate(verts)}
    edges = [(a, b) for a in range(10) for b in range(a + 1, 10)
             if not set(verts[a]) & set(verts[b])]
    gens = []
    for s in ([1, 0, 2, 3, 4], [1, 2, 3, 4, 0]):          # a transposition and a 5-cycle generate S_5
        gens.append([at[tuple(sorted((s[u], s[v])))] for u, v in verts])
    return 10, dense(10, edges), gens


GRAPHS = {"P6": path6, "K23": k23, "petersen": petersen}
MULTI_ORBIT = ["P6", "K23"]


def build(n, seed=0, d_rni=0):
    return LGM(d=D, layers=LAYERS, heads=HEADS, d_rni=d_rni, seed=seed).double().eval()


def graph_of(A):
    return RawGraph.from_dense(A)


# ------------------------------------------------------------------ the group machinery itself

@pytest.mark.parametrize("name,order,n_orb,p_orb", [("P6", 2, 3, 9), ("K23", 12, 2, 3),
                                                    ("petersen", 120, 1, 2)])
def test_hardcoded_generators_produce_the_expected_automorphism_group(name, order, n_orb, p_orb):
    n, A, gens = GRAPHS[name]()
    group = close_group(gens, n)
    assert len(group) == order
    for p in group:                                    # every element really is an automorphism
        idx = torch.tensor(p)
        assert torch.equal(A[idx][:, idx], A), f"{name}: {p} does not preserve the edge set"
    assert len(node_orbits(group, n)) == n_orb
    assert len(pair_orbits(group, n)) == p_orb


def test_node_orbit_equivalence_does_not_imply_pair_equivalence():
    """The counterexample that dictates the shape of every assertion below."""
    n, A, gens = petersen()
    group = close_group(gens, n)
    assert len(node_orbits(group, n)) == 1, "Petersen is vertex-transitive"
    orbs = sorted(len(o) for o in pair_orbits(group, n))
    assert orbs == [15, 30], "adjacent and non-adjacent pairs are separate orbits"


# ------------------------------------------------------------------ equivariance

@pytest.mark.parametrize("name", list(GRAPHS))
def test_output_is_permutation_equivariant(name):
    n, A, _ = GRAPHS[name]()
    m = build(n)
    perm = torch.randperm(n, generator=torch.Generator().manual_seed(7))
    with torch.no_grad():
        s = m(graph_of(A))
        sp = m(graph_of(A[perm][:, perm]))
    assert (sp - s[perm][:, perm]).abs().max() < TOL


@pytest.mark.parametrize("name", list(GRAPHS))
def test_edge_index_column_order_does_not_matter(name):
    """Companion to the above, so a failure is localisable to node relabelling vs edge ordering."""
    n, A, _ = GRAPHS[name]()
    m, g = build(n), graph_of(A)
    cols = torch.randperm(g.edge_index.shape[1], generator=torch.Generator().manual_seed(3))
    with torch.no_grad():
        a = m(g)
        b = m(RawGraph(n, g.edge_index[:, cols]))
    assert (a - b).abs().max() < TOL


# ------------------------------------------------------------------ the automorphism invariant

@pytest.mark.parametrize("name", MULTI_ORBIT)
def test_node_states_are_constant_on_node_orbits(name):
    n, A, gens = GRAPHS[name]()
    m = build(n)
    with torch.no_grad():
        z = m.node_states(graph_of(A))
    orbits = node_orbits(close_group(gens, n), n)
    within = max((z[u] - z[v]).abs().max().item()
                 for o in orbits for u in o for v in o)
    between = min((z[u] - z[v]).abs().max().item()
                  for a, o in enumerate(orbits) for b, p in enumerate(orbits) if a < b
                  for u in o for v in p)
    assert within < TOL, f"{name}: node states differ within an orbit by {within:.2e}"
    # self-calibrating non-vacuity guard: a collapsed constant-output model fails this, not the above
    assert between > 1000 * max(within, 1e-300), \
        f"{name}: orbits are not separated (between {between:.2e} vs within {within:.2e})"


@pytest.mark.parametrize("name", MULTI_ORBIT)
def test_scores_are_constant_on_pair_orbits(name):
    n, A, gens = GRAPHS[name]()
    m = build(n)
    with torch.no_grad():
        s = m(graph_of(A))
    s = (s + s.T) / 2
    orbits = pair_orbits(close_group(gens, n), n)
    within = max(max(s[i, j] for i, j in o) - min(s[i, j] for i, j in o) for o in orbits)
    assert within < TOL, f"{name}: scores differ within a pair orbit by {within:.2e}"
    # non-vacuity: at least two orbits must actually take different values
    vals = sorted(s[o[0][0], o[0][1]].item() for o in orbits)
    assert vals[-1] - vals[0] > 1000 * max(within.item(), 1e-300)
    # and no distinctness is asserted ACROSS orbits: several orbits legitimately coincide


def test_vertex_transitive_graphs_collapse_to_a_constant():
    """Documented degeneracy, not a symmetry test: with a node-state-only decoder, a vertex-
    transitive graph forces every node state equal and hence one constant score for every pair.
    This is why Petersen must NOT carry the orbit assertion -- a broken model passes it."""
    n, A, _ = petersen()
    m = build(n)
    with torch.no_grad():
        z, s = m.node_states(graph_of(A)), m(graph_of(A))
    assert (z - z[0]).abs().max() < TOL
    iu = torch.triu_indices(n, n, 1)
    v = s[iu[0], iu[1]]
    assert (v.max() - v.min()) < TOL


# ------------------------------------------------------------------ random node initialisation

def test_rni_is_jointly_equivariant_when_the_noise_is_permuted_too():
    """RNI is equivariant in DISTRIBUTION, not per sample. Exposing the noise as an explicit
    argument turns that into a hard assertion: permute the graph and its noise together."""
    n, A, _ = petersen()
    m = build(n, d_rni=8)
    z = torch.randn(n, 8, dtype=torch.float64, generator=torch.Generator().manual_seed(1))
    perm = torch.randperm(n, generator=torch.Generator().manual_seed(2))
    with torch.no_grad():
        s = m(graph_of(A), z)
        sp = m(graph_of(A[perm][:, perm]), z[perm])
    assert (sp - s[perm][:, perm]).abs().max() < TOL


def test_rni_breaks_orbit_symmetry_and_the_symmetric_arm_does_not():
    """What RNI is FOR, stated as a test. No claim that it helps any metric -- whether the broken
    symmetry is useful is the empirical question Phase 8 measures, never asserts."""
    n, A, _ = petersen()
    z = torch.randn(n, 8, dtype=torch.float64, generator=torch.Generator().manual_seed(1))
    with torch.no_grad():
        plain = build(n).node_states(graph_of(A))
        rni = build(n, d_rni=8).node_states(graph_of(A), z)
    assert (plain - plain[0]).abs().max() < TOL
    assert (rni - rni[0]).abs().max() > 1e-3


# ------------------------------------------------------------------ negative control

def test_the_phase_1_to_7_e1_encoder_is_not_equivariant():
    """Pinned so the known limitation is an expectation rather than a surprise: E1Linear is
    nn.Linear(n_nodes, d) over adjacency ROWS, so permuting nodes permutes its input columns. This
    is why the Phase-8 gates target g2l.lgm directly and never route through build_model."""
    from g2l.encoders import E1Linear
    n, A, _ = path6()
    enc = E1Linear(n, D, gain=1.0).double().eval()
    perm = torch.randperm(n, generator=torch.Generator().manual_seed(5))
    with torch.no_grad():
        a, b = enc(A), enc(A[perm][:, perm])
    assert (b - a[perm]).abs().max() > 1e-3
